<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta http-equiv="X-UA-Compatible" content="ie=edge"> -->
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div id='column'>
    Menu
    <a href="<?php echo $this->url(array('controller' => 'book' , 'action' => 'list')) ?>">Books</a>
    <a href="<?php echo $this->url(array('controller' => 'authentication' , 'action' => 'logout')) ?>">Logout</a>

    </div>
    <div id='content'>
    Content Space
    <?php echo $this->layout()->content; ?>
    </div>
    <div id='footer'>
    Footer
    </div>
</body>
</html>